version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-restaurant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    ports:
      - '5432:5432'
    networks:
      - restaurant-net

  nestjs:
    build: .
    container_name: restaurant-nest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: restaurant
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
